import {type GraphLink} from "trgraph"

export const O1_GRAPH_LINKS = [
  "mina:field",
  "mina:fields",
  "mina:bool",
  "mina:publickey",
  "mina:privatekey",
  "mina:signature",
  "mina:string",
  "mina:uint64",
  "uint16-mina:field",
  "uint32-mina:field",
  "uint64-mina:field",
  "uint128-mina:field",
  "uint256-mina:field",
  "uint-mina:field",
  "mina:field-uint256",
  "mina:field-uint",
  "uint16-mina:uint64",
  "uint32-mina:uint64",
  "uint64-mina:uint64",
  "uint-mina:uint64",
  "mina:uint64-uint64",
  "mina:uint64-uint128",
  "mina:uint64-uint256",
  "mina:uint64-uint",
  "utf8-mina:string",
  "ascii-mina:string",
  "mina:string-ascii",
  "mina:uint64-mina:fields",
  "mina:fields-mina:uint64",
  "mina:uint64-mina:field",
  "mina:field-mina:uint64",
  "base58-mina:signature",
  "mina:signature-base58",
  "mina:signature-mina:fields",
  "mina:fields-mina:signature",
  "base58-mina:publickey",
  "mina:publickey-base58",
  "mina:publickey-mina:fields",
  "mina:fields-mina:publickey",
  "base58-mina:privatekey",
  "mina:privatekey-base58",
  "mina:privatekey-mina:fields",
  "mina:fields-mina:privatekey",
  "boolean-mina:bool",
  "mina:bool-mina:field",
  "mina:bool-mina:fields",
  "mina:fields-mina:bool",
  "mina:bool-boolean",
  "mina:mod.order",
  "mina:string-mina:fields",
  "mina:fields-mina:string"
] as const

export type O1GraphLink = typeof O1_GRAPH_LINKS[number] | GraphLink